FROM ubuntu:latest

WORKDIR /app
RUN apt-get update && apt-get install -y procps wget

# Add build arg for download URL, comes from github actions
ARG DOWNLOAD_URL

# Copy and run download script
COPY docker/scripts/install-drifted.sh .
RUN chown 1000:1000 /app/install-drifted.sh && chmod +x /app/install-drifted.sh

# Pass download URL as environment variable
ENV DOWNLOAD_URL=${DOWNLOAD_URL}

# Switch to ubuntu user
USER 1000:1000

CMD ["./install-drifted.sh"]