FROM ubuntu:latest

WORKDIR /app
RUN apt-get update && apt-get install -y procps wget curl

# Add build arg for download URL
ARG DOWNLOAD_URL

# Download the binary
RUN curl -L -o drifted ${DOWNLOAD_URL} && \
    chmod +x drifted && \
    chown 1000:1000 drifted

# Switch to ubuntu user
USER 1000:1000

CMD ["./drifted"]
