# Build stage
FROM gcc:latest as builder
WORKDIR /build
COPY . .
RUN gcc -o drifted src/main.c

# Final stage
FROM ubuntu:latest

WORKDIR /app
RUN apt-get update && apt-get install -y procps wget

COPY --from=builder /build/drifted .
RUN chown 1000:1000 /app/drifted && chmod +x /app/drifted

# Switch to ubuntu user
USER 1000:1000

CMD ["./drifted"]
