name: Docker Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for no-drift image
        id: meta-no-drift
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            suffix=-no-drift

      - name: Extract metadata for drifted image
        id: meta-drifted
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            suffix=-drifted

      - name: Build and push no-drift image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.no-drift
          push: true
          tags: ${{ steps.meta-no-drift.outputs.tags }}
          labels: ${{ steps.meta-no-drift.outputs.labels }}
          build-args: |
            BUILD_TYPE=no-drift

      - name: Build and push drifted image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.drifted
          push: true
          tags: ${{ steps.meta-drifted.outputs.tags }}
          labels: ${{ steps.meta-drifted.outputs.labels }}
          build-args: |
            BUILD_TYPE=drifted 