name: Release

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
    - name: Install just
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

    - name: Build
      run: just build ${{ env.VERSION }}
      
    - name: Debug Info
      run: |
        echo "GitHub Ref: $GITHUB_REF"
        echo "Version: $VERSION"
        echo "Files to upload:"
        ls -la build/

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/drifted
        name: Drifted Binary v${{ env.VERSION }}
        body: |
          Drifted Binary Release v${{ env.VERSION }}
          
          Binary is compiled for Linux x86_64
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}